export const todoTypes = {
    DESCRIPTION_CHANGED: 'DESCRIPTION_CHANGED',

    ADD_TASK: 'ADD_TASK',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_ERROR: 'ADD_TASK_ERROR',

    SEARCH_TASK: 'SEARCH_TASK',
    SEARCH_TASK_SUCCESS: 'SEARCH_TASK_SUCCESS',
    SEARCH_TASK_ERROR: 'SEARCH_TASK_ERROR',


    DONE_TASK: 'DONE_TASK',
    DONE_TASK_SUCCESS: 'DONE_TASK_SUCCESS',
    DONE_TASK_ERROR: 'DONE_TASK_ERROR',


    REMOVE_TASK: 'REMOVE_TASK',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
    REMOVE_TASK_ERROR: 'REMOVE_TASK_ERROR'
}